# Generated by Django 3.2.8 on 2021-10-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('options', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=256)),
                ('key', models.CharField(max_length=128)),
                ('auth', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('unsubscribed', 'Unsubscribed')], default='active', max_length=32)),
            ],
        ),
    ]
