# Generated by Django 3.2.8 on 2021-10-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='options',
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Expired'), ('3', 'Unsubscribed')], max_length=20),
        ),
    ]
